pkgname = "dbmodels"
output = "repository/dbmodels"
wipe = true
no-tests = true
add-enum-types = true

[mysql]
dbname  = "phimtor"
host    = "localhost"
port    = 3306
user    = "root"
pass    = "changeme"
sslmode = "false"
blacklist = ["schema_migrations"]

