// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// ViewShow is an object representing the database table.
type ViewShow struct {
	ID            int64         `boil:"id" json:"id" toml:"id" yaml:"id"`
	Title         string        `boil:"title" json:"title" toml:"title" yaml:"title"`
	OriginalTitle string        `boil:"original_title" json:"original_title" toml:"original_title" yaml:"original_title"`
	PosterPath    string        `boil:"poster_path" json:"poster_path" toml:"poster_path" yaml:"poster_path"`
	Type          ViewShowsType `boil:"type" json:"type" toml:"type" yaml:"type"`
	AirDate       null.Time     `boil:"air_date" json:"air_date,omitempty" toml:"air_date" yaml:"air_date,omitempty"`
	Runtime       null.Int      `boil:"runtime" json:"runtime,omitempty" toml:"runtime" yaml:"runtime,omitempty"`
	VoteAverage   float32       `boil:"vote_average" json:"vote_average" toml:"vote_average" yaml:"vote_average"`
	Quality       string        `boil:"quality" json:"quality" toml:"quality" yaml:"quality"`
	MovieID       null.Int64    `boil:"movie_id" json:"movie_id,omitempty" toml:"movie_id" yaml:"movie_id,omitempty"`
	TVSeriesID    null.Int64    `boil:"tv_series_id" json:"tv_series_id,omitempty" toml:"tv_series_id" yaml:"tv_series_id,omitempty"`
	SeasonNumber  null.Int      `boil:"season_number" json:"season_number,omitempty" toml:"season_number" yaml:"season_number,omitempty"`
	EpisodeNumber null.Int      `boil:"episode_number" json:"episode_number,omitempty" toml:"episode_number" yaml:"episode_number,omitempty"`
	CreatedAt     time.Time     `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt     time.Time     `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *viewShowR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L viewShowL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ViewShowColumns = struct {
	ID            string
	Title         string
	OriginalTitle string
	PosterPath    string
	Type          string
	AirDate       string
	Runtime       string
	VoteAverage   string
	Quality       string
	MovieID       string
	TVSeriesID    string
	SeasonNumber  string
	EpisodeNumber string
	CreatedAt     string
	UpdatedAt     string
}{
	ID:            "id",
	Title:         "title",
	OriginalTitle: "original_title",
	PosterPath:    "poster_path",
	Type:          "type",
	AirDate:       "air_date",
	Runtime:       "runtime",
	VoteAverage:   "vote_average",
	Quality:       "quality",
	MovieID:       "movie_id",
	TVSeriesID:    "tv_series_id",
	SeasonNumber:  "season_number",
	EpisodeNumber: "episode_number",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
}

var ViewShowTableColumns = struct {
	ID            string
	Title         string
	OriginalTitle string
	PosterPath    string
	Type          string
	AirDate       string
	Runtime       string
	VoteAverage   string
	Quality       string
	MovieID       string
	TVSeriesID    string
	SeasonNumber  string
	EpisodeNumber string
	CreatedAt     string
	UpdatedAt     string
}{
	ID:            "view_shows.id",
	Title:         "view_shows.title",
	OriginalTitle: "view_shows.original_title",
	PosterPath:    "view_shows.poster_path",
	Type:          "view_shows.type",
	AirDate:       "view_shows.air_date",
	Runtime:       "view_shows.runtime",
	VoteAverage:   "view_shows.vote_average",
	Quality:       "view_shows.quality",
	MovieID:       "view_shows.movie_id",
	TVSeriesID:    "view_shows.tv_series_id",
	SeasonNumber:  "view_shows.season_number",
	EpisodeNumber: "view_shows.episode_number",
	CreatedAt:     "view_shows.created_at",
	UpdatedAt:     "view_shows.updated_at",
}

// Generated where

type whereHelperViewShowsType struct{ field string }

func (w whereHelperViewShowsType) EQ(x ViewShowsType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelperViewShowsType) NEQ(x ViewShowsType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperViewShowsType) LT(x ViewShowsType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperViewShowsType) LTE(x ViewShowsType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperViewShowsType) GT(x ViewShowsType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperViewShowsType) GTE(x ViewShowsType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperViewShowsType) IN(slice []ViewShowsType) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperViewShowsType) NIN(slice []ViewShowsType) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpernull_Int struct{ field string }

func (w whereHelpernull_Int) EQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int) NEQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int) LT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int) LTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int) GT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int) GTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var ViewShowWhere = struct {
	ID            whereHelperint64
	Title         whereHelperstring
	OriginalTitle whereHelperstring
	PosterPath    whereHelperstring
	Type          whereHelperViewShowsType
	AirDate       whereHelpernull_Time
	Runtime       whereHelpernull_Int
	VoteAverage   whereHelperfloat32
	Quality       whereHelperstring
	MovieID       whereHelpernull_Int64
	TVSeriesID    whereHelpernull_Int64
	SeasonNumber  whereHelpernull_Int
	EpisodeNumber whereHelpernull_Int
	CreatedAt     whereHelpertime_Time
	UpdatedAt     whereHelpertime_Time
}{
	ID:            whereHelperint64{field: "`view_shows`.`id`"},
	Title:         whereHelperstring{field: "`view_shows`.`title`"},
	OriginalTitle: whereHelperstring{field: "`view_shows`.`original_title`"},
	PosterPath:    whereHelperstring{field: "`view_shows`.`poster_path`"},
	Type:          whereHelperViewShowsType{field: "`view_shows`.`type`"},
	AirDate:       whereHelpernull_Time{field: "`view_shows`.`air_date`"},
	Runtime:       whereHelpernull_Int{field: "`view_shows`.`runtime`"},
	VoteAverage:   whereHelperfloat32{field: "`view_shows`.`vote_average`"},
	Quality:       whereHelperstring{field: "`view_shows`.`quality`"},
	MovieID:       whereHelpernull_Int64{field: "`view_shows`.`movie_id`"},
	TVSeriesID:    whereHelpernull_Int64{field: "`view_shows`.`tv_series_id`"},
	SeasonNumber:  whereHelpernull_Int{field: "`view_shows`.`season_number`"},
	EpisodeNumber: whereHelpernull_Int{field: "`view_shows`.`episode_number`"},
	CreatedAt:     whereHelpertime_Time{field: "`view_shows`.`created_at`"},
	UpdatedAt:     whereHelpertime_Time{field: "`view_shows`.`updated_at`"},
}

// ViewShowRels is where relationship names are stored.
var ViewShowRels = struct {
}{}

// viewShowR is where relationships are stored.
type viewShowR struct {
}

// NewStruct creates a new relationship struct
func (*viewShowR) NewStruct() *viewShowR {
	return &viewShowR{}
}

// viewShowL is where Load methods for each relationship are stored.
type viewShowL struct{}

var (
	viewShowAllColumns            = []string{"id", "title", "original_title", "poster_path", "type", "air_date", "runtime", "vote_average", "quality", "movie_id", "tv_series_id", "season_number", "episode_number", "created_at", "updated_at"}
	viewShowColumnsWithoutDefault = []string{"title", "original_title", "poster_path", "type", "air_date", "runtime", "vote_average", "quality", "movie_id", "tv_series_id", "season_number", "episode_number"}
	viewShowColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	viewShowPrimaryKeyColumns     = []string{"id"}
	viewShowGeneratedColumns      = []string{}
)

type (
	// ViewShowSlice is an alias for a slice of pointers to ViewShow.
	// This should almost always be used instead of []ViewShow.
	ViewShowSlice []*ViewShow
	// ViewShowHook is the signature for custom ViewShow hook methods
	ViewShowHook func(context.Context, boil.ContextExecutor, *ViewShow) error

	viewShowQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	viewShowType                 = reflect.TypeOf(&ViewShow{})
	viewShowMapping              = queries.MakeStructMapping(viewShowType)
	viewShowPrimaryKeyMapping, _ = queries.BindMapping(viewShowType, viewShowMapping, viewShowPrimaryKeyColumns)
	viewShowInsertCacheMut       sync.RWMutex
	viewShowInsertCache          = make(map[string]insertCache)
	viewShowUpdateCacheMut       sync.RWMutex
	viewShowUpdateCache          = make(map[string]updateCache)
	viewShowUpsertCacheMut       sync.RWMutex
	viewShowUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var viewShowAfterSelectMu sync.Mutex
var viewShowAfterSelectHooks []ViewShowHook

var viewShowBeforeInsertMu sync.Mutex
var viewShowBeforeInsertHooks []ViewShowHook
var viewShowAfterInsertMu sync.Mutex
var viewShowAfterInsertHooks []ViewShowHook

var viewShowBeforeUpdateMu sync.Mutex
var viewShowBeforeUpdateHooks []ViewShowHook
var viewShowAfterUpdateMu sync.Mutex
var viewShowAfterUpdateHooks []ViewShowHook

var viewShowBeforeDeleteMu sync.Mutex
var viewShowBeforeDeleteHooks []ViewShowHook
var viewShowAfterDeleteMu sync.Mutex
var viewShowAfterDeleteHooks []ViewShowHook

var viewShowBeforeUpsertMu sync.Mutex
var viewShowBeforeUpsertHooks []ViewShowHook
var viewShowAfterUpsertMu sync.Mutex
var viewShowAfterUpsertHooks []ViewShowHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ViewShow) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range viewShowAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ViewShow) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range viewShowBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ViewShow) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range viewShowAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ViewShow) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range viewShowBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ViewShow) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range viewShowAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ViewShow) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range viewShowBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ViewShow) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range viewShowAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ViewShow) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range viewShowBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ViewShow) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range viewShowAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddViewShowHook registers your hook function for all future operations.
func AddViewShowHook(hookPoint boil.HookPoint, viewShowHook ViewShowHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		viewShowAfterSelectMu.Lock()
		viewShowAfterSelectHooks = append(viewShowAfterSelectHooks, viewShowHook)
		viewShowAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		viewShowBeforeInsertMu.Lock()
		viewShowBeforeInsertHooks = append(viewShowBeforeInsertHooks, viewShowHook)
		viewShowBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		viewShowAfterInsertMu.Lock()
		viewShowAfterInsertHooks = append(viewShowAfterInsertHooks, viewShowHook)
		viewShowAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		viewShowBeforeUpdateMu.Lock()
		viewShowBeforeUpdateHooks = append(viewShowBeforeUpdateHooks, viewShowHook)
		viewShowBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		viewShowAfterUpdateMu.Lock()
		viewShowAfterUpdateHooks = append(viewShowAfterUpdateHooks, viewShowHook)
		viewShowAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		viewShowBeforeDeleteMu.Lock()
		viewShowBeforeDeleteHooks = append(viewShowBeforeDeleteHooks, viewShowHook)
		viewShowBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		viewShowAfterDeleteMu.Lock()
		viewShowAfterDeleteHooks = append(viewShowAfterDeleteHooks, viewShowHook)
		viewShowAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		viewShowBeforeUpsertMu.Lock()
		viewShowBeforeUpsertHooks = append(viewShowBeforeUpsertHooks, viewShowHook)
		viewShowBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		viewShowAfterUpsertMu.Lock()
		viewShowAfterUpsertHooks = append(viewShowAfterUpsertHooks, viewShowHook)
		viewShowAfterUpsertMu.Unlock()
	}
}

// One returns a single viewShow record from the query.
func (q viewShowQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ViewShow, error) {
	o := &ViewShow{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: failed to execute a one query for view_shows")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ViewShow records from the query.
func (q viewShowQuery) All(ctx context.Context, exec boil.ContextExecutor) (ViewShowSlice, error) {
	var o []*ViewShow

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbmodels: failed to assign all query results to ViewShow slice")
	}

	if len(viewShowAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ViewShow records in the query.
func (q viewShowQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to count view_shows rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q viewShowQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: failed to check if view_shows exists")
	}

	return count > 0, nil
}

// ViewShows retrieves all the records using an executor.
func ViewShows(mods ...qm.QueryMod) viewShowQuery {
	mods = append(mods, qm.From("`view_shows`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`view_shows`.*"})
	}

	return viewShowQuery{q}
}

// FindViewShow retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindViewShow(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*ViewShow, error) {
	viewShowObj := &ViewShow{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `view_shows` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, viewShowObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: unable to select from view_shows")
	}

	if err = viewShowObj.doAfterSelectHooks(ctx, exec); err != nil {
		return viewShowObj, err
	}

	return viewShowObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ViewShow) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodels: no view_shows provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(viewShowColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	viewShowInsertCacheMut.RLock()
	cache, cached := viewShowInsertCache[key]
	viewShowInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			viewShowAllColumns,
			viewShowColumnsWithDefault,
			viewShowColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(viewShowType, viewShowMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(viewShowType, viewShowMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `view_shows` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `view_shows` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `view_shows` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, viewShowPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to insert into view_shows")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == viewShowMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to populate default values for view_shows")
	}

CacheNoHooks:
	if !cached {
		viewShowInsertCacheMut.Lock()
		viewShowInsertCache[key] = cache
		viewShowInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ViewShow.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ViewShow) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	viewShowUpdateCacheMut.RLock()
	cache, cached := viewShowUpdateCache[key]
	viewShowUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			viewShowAllColumns,
			viewShowPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbmodels: unable to update view_shows, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `view_shows` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, viewShowPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(viewShowType, viewShowMapping, append(wl, viewShowPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update view_shows row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by update for view_shows")
	}

	if !cached {
		viewShowUpdateCacheMut.Lock()
		viewShowUpdateCache[key] = cache
		viewShowUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q viewShowQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all for view_shows")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected for view_shows")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ViewShowSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbmodels: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), viewShowPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `view_shows` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, viewShowPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all in viewShow slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected all in update all viewShow")
	}
	return rowsAff, nil
}

var mySQLViewShowUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ViewShow) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodels: no view_shows provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(viewShowColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLViewShowUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	viewShowUpsertCacheMut.RLock()
	cache, cached := viewShowUpsertCache[key]
	viewShowUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			viewShowAllColumns,
			viewShowColumnsWithDefault,
			viewShowColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			viewShowAllColumns,
			viewShowPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("dbmodels: unable to upsert view_shows, could not build update column list")
		}

		ret := strmangle.SetComplement(viewShowAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`view_shows`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `view_shows` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(viewShowType, viewShowMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(viewShowType, viewShowMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to upsert for view_shows")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == viewShowMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(viewShowType, viewShowMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to retrieve unique values for view_shows")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to populate default values for view_shows")
	}

CacheNoHooks:
	if !cached {
		viewShowUpsertCacheMut.Lock()
		viewShowUpsertCache[key] = cache
		viewShowUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ViewShow record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ViewShow) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbmodels: no ViewShow provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), viewShowPrimaryKeyMapping)
	sql := "DELETE FROM `view_shows` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete from view_shows")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by delete for view_shows")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q viewShowQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbmodels: no viewShowQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from view_shows")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for view_shows")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ViewShowSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(viewShowBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), viewShowPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `view_shows` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, viewShowPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from viewShow slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for view_shows")
	}

	if len(viewShowAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ViewShow) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindViewShow(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ViewShowSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ViewShowSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), viewShowPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `view_shows`.* FROM `view_shows` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, viewShowPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to reload all in ViewShowSlice")
	}

	*o = slice

	return nil
}

// ViewShowExists checks if the ViewShow row exists.
func ViewShowExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `view_shows` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: unable to check if view_shows exists")
	}

	return exists, nil
}

// Exists checks if the ViewShow row exists.
func (o *ViewShow) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ViewShowExists(ctx, exec, o.ID)
}
