// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package ports

// Defines values for BasicInfoShowType.
const (
	BasicInfoShowTypeMovie  BasicInfoShowType = "movie"
	BasicInfoShowTypeSeries BasicInfoShowType = "series"
)

// BasicInfo defines model for BasicInfo.
type BasicInfo struct {
	CurrentEpisode    int               `json:"currentEpisode"`
	DurationInMinutes int               `json:"durationInMinutes"`
	Id                int64             `json:"id"`
	OriginalTitle     string            `json:"originalTitle"`
	PosterLink        string            `json:"posterLink"`
	Quantity          string            `json:"quantity"`
	ReleaseYear       int               `json:"releaseYear"`
	Score    float32           `json:"score"`
	ShowType BasicInfoShowType `json:"showType"`
	Title    string            `json:"title"`
	TotalEpisodes     int               `json:"totalEpisodes"`
}

// BasicInfoShowType defines model for BasicInfo.ShowType.
type BasicInfoShowType string

// Movie defines model for Movie.
type Movie struct {
	BasicInfo   BasicInfo `json:"basicInfo"`
	Description string    `json:"description"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Page         int   `json:"page"`
	TotalPages   int   `json:"totalPages"`
	TotalResults int64 `json:"totalResults"`
}

// ListShowsParams defines parameters for ListShows.
type ListShowsParams struct {
	Name *string `form:"name,omitempty" json:"name,omitempty"`
	Page *int    `form:"page,omitempty" json:"page,omitempty"`
}
