// Package http2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package http2

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ShowQuality.
const (
	N1080p ShowQuality = "1080p"
	N4k    ShowQuality = "4k"
	N720p  ShowQuality = "720p"
)

// Defines values for ShowType.
const (
	ShowTypeEpisode  ShowType = "episode"
	ShowTypeMovie    ShowType = "movie"
	ShowTypeTvSeries ShowType = "tv-series"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Genre defines model for Genre.
type Genre struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

// Movie defines model for Movie.
type Movie struct {
	BackdropLink  string             `json:"backdropLink"`
	Genres        []Genre            `json:"genres"`
	Id            int64              `json:"id"`
	OriginalTitle string             `json:"originalTitle"`
	Overview      string             `json:"overview"`
	PosterLink    string             `json:"posterLink"`
	ReleaseDate   openapi_types.Date `json:"releaseDate"`
	Runtime       int                `json:"runtime"`
	Status        string             `json:"status"`
	Tagline       string             `json:"tagline"`
	Title         string             `json:"title"`
	VideoID       int64              `json:"videoID"`
	VoteAverage   float32            `json:"voteAverage"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Page         int   `json:"page"`
	TotalPages   int   `json:"totalPages"`
	TotalResults int64 `json:"totalResults"`
}

// PremiumTorrentLink defines model for PremiumTorrentLink.
type PremiumTorrentLink struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Priority int    `json:"priority"`
}

// Show defines model for Show.
type Show struct {
	AirDate       openapi_types.Date `json:"airDate"`
	EpisodeNumber int                `json:"episodeNumber"`
	Id            int64              `json:"id"`
	MovieID       int64              `json:"movieID"`
	OriginalTitle string             `json:"originalTitle"`
	PosterLink    string             `json:"posterLink"`
	Quality       ShowQuality        `json:"quality"`
	Runtime       int                `json:"runtime"`
	SeasonNumber  int                `json:"seasonNumber"`
	Title         string             `json:"title"`
	TvSeriesID    int64              `json:"tvSeriesID"`
	Type          ShowType           `json:"type"`
	VoteAverage   float32            `json:"voteAverage"`
}

// ShowQuality defines model for Show.Quality.
type ShowQuality string

// ShowType defines model for Show.Type.
type ShowType string

// Subtitle defines model for Subtitle.
type Subtitle struct {
	Id       int64  `json:"id"`
	Language string `json:"language"`
	Link     string `json:"link"`
	Name     string `json:"name"`
	Owner    string `json:"owner"`
	Priority int    `json:"priority"`
}

// TVSeason defines model for TVSeason.
type TVSeason struct {
	AirDate  *openapi_types.Date `json:"airDate,omitempty"`
	Episodes []struct {
		AirDate       *openapi_types.Date `json:"airDate,omitempty"`
		EpisodeNumber int                 `json:"episodeNumber"`
		Id            int64               `json:"id"`
		Name          string              `json:"name"`
		Overview      string              `json:"overview"`
		Runtime       int                 `json:"runtime"`
		StillLink     string              `json:"stillLink"`
		VideoID       int64               `json:"videoID"`
		VoteAverage   float32             `json:"voteAverage"`
	} `json:"episodes"`
	Id           int64   `json:"id"`
	Name         string  `json:"name"`
	Overview     string  `json:"overview"`
	PosterLink   string  `json:"posterLink"`
	SeasonNumber int     `json:"seasonNumber"`
	VoteAverage  float32 `json:"voteAverage"`
}

// TorrentLink defines model for TorrentLink.
type TorrentLink struct {
	FileIndex      int    `json:"fileIndex"`
	Id             int64  `json:"id"`
	Link           string `json:"link"`
	Name           string `json:"name"`
	Priority       int    `json:"priority"`
	RequirePremium bool   `json:"requirePremium"`
}

// TvSeries defines model for TvSeries.
type TvSeries struct {
	BackdropLink     string              `json:"backdropLink"`
	FirstAirDate     *openapi_types.Date `json:"firstAirDate,omitempty"`
	Genres           []Genre             `json:"genres"`
	Id               int64               `json:"id"`
	LastAirDate      *openapi_types.Date `json:"lastAirDate,omitempty"`
	Name             string              `json:"name"`
	NumberOfEpisodes int                 `json:"numberOfEpisodes"`
	NumberOfSeasons  int                 `json:"numberOfSeasons"`
	OriginalName     string              `json:"originalName"`
	Overview         string              `json:"overview"`
	PosterLink       string              `json:"posterLink"`
	Seasons          []struct {
		AirDate      *openapi_types.Date `json:"airDate,omitempty"`
		Id           int64               `json:"id"`
		Name         string              `json:"name"`
		Overview     string              `json:"overview"`
		PosterLink   string              `json:"posterLink"`
		SeasonNumber int                 `json:"seasonNumber"`
		VoteAverage  float32             `json:"voteAverage"`
	} `json:"seasons"`
	Status      string  `json:"status"`
	Tagline     string  `json:"tagline"`
	VoteAverage float32 `json:"voteAverage"`
}

// Video defines model for Video.
type Video struct {
	Id                  int64                `json:"id"`
	PremiumTorrentLinks []PremiumTorrentLink `json:"premiumTorrentLinks"`
	Subtitles           []Subtitle           `json:"subtitles"`
	TorrentLinks        []TorrentLink        `json:"torrentLinks"`
}

// Page defines model for page.
type Page = int

// PageSize defines model for pageSize.
type PageSize = int

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// GetLatestEpisodesParams defines parameters for GetLatestEpisodes.
type GetLatestEpisodesParams struct {
	Page     *Page     `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetLatestMoviesParams defines parameters for GetLatestMovies.
type GetLatestMoviesParams struct {
	Page     *Page     `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetLatestTvSeriesParams defines parameters for GetLatestTvSeries.
type GetLatestTvSeriesParams struct {
	Page     *Page     `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// SearchShowsParams defines parameters for SearchShows.
type SearchShowsParams struct {
	Query    string    `form:"query" json:"query"`
	Page     *Page     `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}
