name: Build flutter app

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      server_address:
        description: 'Address of the server'
        required: true
        type: string

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    env:
      SERVER_ADDR: ${{ inputs.server_address }}
    defaults:
      run:
        working-directory: phimtor_app
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 50

      # Store the version, stripping any v-prefix
      - name: Write release version
        run: |
          VERSION=$(git describe --tags --always --match='v[0-9]*.[0-9]*.[0-9]*' 2> /dev/null | sed 's/^.//')
          if [ -z "$VERSION" ] || ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-.+)*$ ]]; then
            VERSION="0.0.1-$(git rev-parse --short HEAD)"
          fi
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Write version file
        if: runner.os == 'Linux'
        run: echo $VERSION > ${{github.workspace}}/VERSION.txt
        shell: bash

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          cache: true

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          check-latest: true
          cache-dependency-path: torrent/src/go.mod

      - name: Show go env
        run: go env
        shell: bash

      - name: Patch Linux
        if: runner.os == 'Linux'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libglu1-mesa clang cmake ninja-build libgtk-3-dev libmpv-dev mpv libfuse2
          version: 1.0

      - name: Flutter doctor
        run: flutter doctor
        shell: bash

      ############################
      # Build for each platform
      ############################
      # Ubuntu
      - name: Build Linux
        if: runner.os == 'Linux'
        run: scripts/build-linux.sh ${{ env.VERSION }} ${{ github.run_attempt }}
        shell: bash

      # Windows
      - name: Install msys2
        id: msys2
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc

      - name: Change path to include ucrt64
        if: runner.os == 'Windows'
        run: |
          echo '${{ steps.msys2.outputs.msys2-location }}\ucrt64\bin' >> $GITHUB_PATH
        shell: bash

      - name: Test g++
        if: runner.os == 'Windows'
        run: |
          which g++
          g++ --version
          echo $PATH
        shell: bash
      - name: Build Windows
        if: runner.os == 'Windows'
        run: scripts/build-windows.sh ${{ env.VERSION }} ${{ github.run_attempt }}
        shell: bash

      - name: Compile .ISS to .EXE Installer
        if: runner.os == 'Windows'
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: phimtor_app/windows/phimtor.iss
          options: /DMyAppVersion=${{ env.VERSION }} /DWorkingDir="${{ github.workspace }}\phimtor_app" /DUCRT64Dir="${{ steps.msys2.outputs.msys2-location }}\ucrt64\bin" /F"PhimTorSetup-${{ env.VERSION }}"

      # MacOS
      - name: Install dependencies
        if: runner.os == 'macOS'
        run: |
          brew install create-dmg
        shell: bash
      - name: Build MacOS
        if: runner.os == 'macOS'
        run: scripts/build-macos.sh ${{ env.VERSION }} ${{ github.run_attempt }}
        shell: bash

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: phimtor_app_${{ runner.os }}
          path: |
            ${{github.workspace}}/phimtor_app/build/*.AppImage
            ${{github.workspace}}\phimtor_app\build\*.exe 
            ${{github.workspace}}/phimtor_app/build/*.pkg
            ${{github.workspace}}/VERSION.txt
