name: Build and deploy server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Golang
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
          check-latest: true
          cache-dependency-path: server/go.mod
      - run: go version
        shell: bash

      # Build server
      - name: Build server
        run: |
          cd server && go build -o server
        shell: bash

      # Upload artifacts
      - name: Upload server
        uses: actions/upload-artifact@v4
        with:
          name: server
          path: server/server

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Install ssh key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        shell: bash

      - name: Download server
        uses: actions/download-artifact@v4
        with:
          name: server

      - name: Deploy server
        run: |
          chmod +x server
          scp server ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ vars.WORKING_DIR }}
        shell: bash
