name: Deploy server

on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'Name to download the artifact'
        required: true
        type: string
      environment:
        description: 'Environment'
        required: true
        type: string
      service_name:
        description: 'Service name'
        required: true
        type: string
    secrets:
      SSH_HOST:
        description: 'SSH host'
        required: true
      SSH_USER:
        description: 'SSH user'
        required: true
      SSH_PRIVATE_KEY:
        description: 'SSH private key'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Install ssh key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
          cat >>~/.ssh/config <<END
          Host server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        shell: bash

      - name: Download server
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: server

      - name: Deploy server
        run: |
          ssh server "systemctl --user stop ${{ inputs.service_name }}"
          scp -r server server:${{ vars.WORKING_DIR }}
          ssh server "chmod +x ${{ vars.WORKING_DIR }}/server/server"
          ssh server "systemctl --user start ${{ inputs.service_name }}"
        shell: bash
