name: Build and deploy server on prod

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build_server.yml

  deploy:
    needs: [build]
    uses: ./.github/workflows/deploy_server.yml
    with:
      artifact_name: ${{ needs.build.outputs.artifact_name }}
      environment: production
      service_name: "phimtor.server.prod.service"
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
