name: Workflow for Prod

permissions:
  contents: write

on:
  release:
    types: [ published ]

jobs:
  build_desktop:
    uses: ./.github/workflows/build_desktop.yml
    with:
      server_address: "https://phimtor.net"
      firebase_api_key: "AIzaSyCSbDOQE6soH-DlOqD2ovrVUWjlzzg6pSA"

  release_desktop:
    needs: [ build_desktop ]
    uses: ./.github/workflows/release_desktop.yml
    with:
      artifact_pattern: ${{ needs.build_desktop.outputs.artifact_pattern }}
      environment: production
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  build_server:
    uses: ./.github/workflows/build_server.yml

  build_admin:
    uses: ./.github/workflows/build_admin.yml

  deploy_server:
    needs: [ build_server, release_desktop ]
    uses: ./.github/workflows/deploy_server.yml
    with:
      artifact_name: ${{ needs.build_server.outputs.artifact_name }}
      environment: production
      service_name: "phimtor.server.prod.service"
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  deploy_admin:
    needs: [ build_admin ]
    uses: ./.github/workflows/deploy_admin.yml
    with:
      artifact_name: ${{ needs.build_admin.outputs.artifact_name }}
      environment: production
      service_name: "phimtor.admin.prod.service"
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}