name: Build Desktop App on Prod

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build_desktop.yml
    with:
      server_address: "https://phimtor.net"
      firebase_api_key: "AIzaSyCSbDOQE6soH-DlOqD2ovrVUWjlzzg6pSA"

  release:
    needs: [build]
    uses: ./.github/workflows/release_desktop.yml
    with:
      artifact_pattern: ${{ needs.build.outputs.artifact_pattern }}
      environment: production
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
