name: Workflow for Dev

permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  build_flutter_app:
    uses: ./.github/workflows/build_flutter_app.yml
    with:
      server_address: "https://dev.phimtor.net"

  release_phimtor_app:
    needs: [ build_flutter_app ]
    uses: ./.github/workflows/release_phimtor_app.yml
    with:
      artifact_pattern: phimtor_app_*
      environment: development
      destination_dir: "phimtor_app"
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  build_server:
    uses: ./.github/workflows/build_server.yml

  build_admin:
    uses: ./.github/workflows/build_admin.yml

  deploy_server:
    needs: [ build_server ]
    uses: ./.github/workflows/deploy_server.yml
    with:
      artifact_name: ${{ needs.build_server.outputs.artifact_name }}
      environment: development
      service_name: "phimtor.server.dev.service"
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  deploy_admin:
    needs: [ build_admin ]
    uses: ./.github/workflows/deploy_admin.yml
    with:
      artifact_name: ${{ needs.build_admin.outputs.artifact_name }}
      environment: development
      service_name: "phimtor.admin.dev.service"
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}