name: Release phimtor app on production

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Install ssh key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
          cat >>~/.ssh/config <<END
          Host server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        shell: bash

      - name: Deploy desktop
        run: |
          ssh server 'mkdir -p ${{ vars.WORKING_DIR }}/phimtor_app'
          ssh server 'cd ${{ vars.WORKING_DIR }} && sed -i "s/$(cat phimtor_app/VERSION.txt)/$(cat phimtor_app_candidate/VERSION.txt)/" landing/index.html'
          ssh server 'rm -rf ${{ vars.WORKING_DIR }}/phimtor_app/*'
          ssh server 'cp -r ${{ vars.WORKING_DIR }}/phimtor_app_candidate/* ${{ vars.WORKING_DIR }}/phimtor_app/'
        shell: bash