name: Workflow for Dev

permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  build-desktop:
    uses: ./.github/workflows/build_desktop.yml
    with:
      server_address: "https://dev.phimtor.net"
      firebase_api_key: "AIzaSyD0OPqFBC2tYvj74wMWvXqoPixSryet2lQ"

  build-server:
    uses: ./.github/workflows/build_server.yml

  release-desktop:
    needs: [ build-desktop ]
    uses: ./.github/workflows/release_desktop.yml
    with:
      artifact_pattern: ${{ needs.build.outputs.artifact_pattern }}
      environment: development
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  deploy-server:
    needs: [ build-server, release-desktop ]
    uses: ./.github/workflows/deploy_server.yml
    with:
      artifact_name: ${{ needs.build.outputs.artifact_name }}
      environment: development
      service_name: "phimtor.server.dev.service"
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}