name: Workflow for Prod

permissions:
  contents: write

on:
  release:
    types: [ published ]

jobs:
  build-desktop:
    uses: ./.github/workflows/build_desktop.yml
    with:
      server_address: "https://phimtor.net"
      firebase_api_key: "AIzaSyCSbDOQE6soH-DlOqD2ovrVUWjlzzg6pSA"

  release-desktop:
    needs: [ build-desktop ]
    uses: ./.github/workflows/release_desktop.yml
    with:
      artifact_pattern: ${{ needs.build.outputs.artifact_pattern }}
      environment: production
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  build-server:
    uses: ./.github/workflows/build_server.yml

  deploy-server:
    needs: [ build-server, release-desktop ]
    uses: ./.github/workflows/deploy_server.yml
    with:
      artifact_name: ${{ needs.build.outputs.artifact_name }}
      environment: production
      service_name: "phimtor.server.prod.service"
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}