.PHONY: openapi-http
openapi-http:
	@./scripts/openapi-http.sh torrent_api src/http http

.PHONY: openapi-dart-client
openapi-dart-client:
	@./scripts/openapi-dart-client.sh torrent_api openapi_client